services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: currency-exchange-app
        working_dir: /var/www/symfony
        volumes:
            - .:/var/www/symfony
        depends_on:
            - postgres

    worker:
        build:
            context: .
            dockerfile: docker/worker/Dockerfile
        container_name: currency-exchange-worker
        volumes:
            - .:/var/www/symfony
        depends_on:
            - app

    nginx:
        image: nginx:latest
        container_name: currency-exchange-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    postgres:
        image: postgres:16
        container_name: currency-exchange-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        volumes:
            - redis-cache:/data

volumes:
    pgdata:
