services:
    php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: currency-exchange-php
        working_dir: /var/www/symfony
        volumes:
            - .:/var/www/symfony
        depends_on:
            - postgres

    nginx:
        image: nginx:latest
        container_name: currency-exchange-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    postgres:
        image: postgres:16
        container_name: currency-exchange-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
